/**
 * 导出所有的action
 */
export default {
  THEME_CHANGE: 'THEME_CHANGE', //修改主题
  THEME_INIT: 'THEME_INIT', //主题初始化
  LOAD_POPULAR: 'POPULAR_REFRESH', //刷新最热数据
  LOAD_POPULAR_FAIL: 'LOAD_POPULAR_FAIL', //加载最热数据失败
  LOAD_POPULAR_SUCCESS: 'LOAD_POPULAR_SUCCESS', //加载最热数据成功
  LOAD_MORE_POPULAR_SUCCESS: 'LOAD_MORE_POPULAR_SUCCESS', // 上拉加载更多成功
  LOAD_MORE_POPULAR_FAIL: 'LOAD_MORE_POPULAR_FAIL', //上拉加载更多失败
  LOAD_TRENDING: 'LOAD_TRENDING', //刷新趋势数据
  LOAD_TRENDING_FAIL: 'LOAD_TRENDINGLOAD_POPULAR_FAIL', //加载趋势数据失败
  LOAD_TRENDING_SUCCESS: 'LOAD_TRENDING_SUCCESS', //加载趋势数据成功
  LOAD_MORE_TRENDING_SUCCESS: 'LOAD_MORE_TRENDING_SUCCESS', // 上拉加载更多趋势数据成功
  LOAD_MORE_TRENDING_FAIL: 'LOAD_MORE_TRENDING_FAIL', //上拉加载更多趋势数据失败
  LOAD_FAVORITE: 'FAVORITE_REFRESH', //加载收藏数据
  LOAD_FAVORITE_FAIL: 'LOAD_FAVORITE_FAIL', //加载收藏数据失败
  LOAD_FAVORITE_SUCCESS: 'LOAD_FAVORITE_SUCCESS', //加载收藏数据成功
};
